"""rename department

Revision ID: 53be9fcfd80d
Revises: 2b8d74e4235e
Create Date: 2025-06-12 21:55:05.191853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53be9fcfd80d'
down_revision = '2b8d74e4235e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.rename_table('departments','department')
    # ### end Alembic commands ###
